name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 
  flutter_svg: ^2.1.0 
  slide_to_act: ^2.0.2 
  get: ^4.7.2 
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  lottie: ^3.3.1
  chow_button: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-SemiBold.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-ExtraBold.ttf
    - assets/images/man.svg
    - assets/icons/appicon.svg
    - assets/animations/splash.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800