// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBvuWqeOkT8IZUxHZiIDC70EnW_Yaqlw',
    appId: '1:98231427895:web:4ea8d422ae5733363570b2',
    messagingSenderId: '98231427895',
    projectId: 'chatapp-ae757',
    authDomain: 'chatapp-ae757.firebaseapp.com',
    storageBucket: 'chatapp-ae757.firebasestorage.app',
    measurementId: 'G-DDKWE52KPH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpD4rn_d_yGlotpygipWTcgUMGD8lJkHw',
    appId: '1:98231427895:ios:abba390150cc1efc3570b2',
    messagingSenderId: '98231427895',
    projectId: 'chatapp-ae757',
    storageBucket: 'chatapp-ae757.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpD4rn_d_yGlotpygipWTcgUMGD8lJkHw',
    appId: '1:98231427895:ios:abba390150cc1efc3570b2',
    messagingSenderId: '98231427895',
    projectId: 'chatapp-ae757',
    storageBucket: 'chatapp-ae757.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYBvuWqeOkT8IZUxHZiIDC70EnW_Yaqlw',
    appId: '1:98231427895:web:0dbb85de92a34d0e3570b2',
    messagingSenderId: '98231427895',
    projectId: 'chatapp-ae757',
    authDomain: 'chatapp-ae757.firebaseapp.com',
    storageBucket: 'chatapp-ae757.firebasestorage.app',
    measurementId: 'G-SXJ8JEYNBY',
  );
}
